first =int(input("Enter first name: "))
second =int(input("Enter last name: "))
print("Addition:",(first+second))
print("Subtraction:",(first-second))
print("Multiplication:",(first*second))
print("Division:",(first/second))
