first =int(input("Enter first number: "))
second =int(input("Enter second number: "))
print("Addition:",(first+second))
print("Subtraction:",(first-second))
print("Multiplication:",(first*second))
print("Division:",(first/second))
